---
homebrew_taps: []

homebrew_packages:
  - git

homebrew_casks:
  - visual-studio-code
  - cursor
  - windsurf
  - zen-browser
  - google-chrome
  - firefox
  - bitwarden
  - whatsapp
  - discord
  - slack
  - claude
  - google-antigravity
  - github
  - rambox

nerd_fonts:
  - font-martian-mono-nerd-font
  - font-droid-sans-mono-nerd-font

nvm_version: v0.39.7
bun_install_url: https://bun.sh/install
docker_desktop_urls:
  arm64: https://desktop.docker.com/mac/main/arm64/Docker.dmg
  x86_64: https://desktop.docker.com/mac/main/amd64/Docker.dmg
docker_dmg_path: /tmp/DockerDesktop.dmg
docker_mount_point: /Volumes/DockerDesktop
lazydocker_binary_url: https://github.com/jesseduffield/lazydocker/releases/latest/download/lazydocker-darwin-amd64.tar.gz
oh_my_posh_install_script: https://ohmyposh.dev/install.sh
oh_my_posh_install_dir: /usr/local/bin
