---
apt_packages:
  - build-essential
  - git
  - curl
  - unzip
  - python3
  - python3-pip
  - snapd
  - ca-certificates
  - gnupg
  - jq
  - tldr
  - docker.io
  - docker-compose-plugin
  - btop
  - fonts-martian-mono
  - fonts-droid-fallback
  - fonts-hack-ttf
  - dconf-cli

nerd_fonts_release: v3.1.1
nerd_fonts_to_install:
  - name: MartianMono
    archive: MartianMono.zip
  - name: DroidSansMono
    archive: DroidSansMono.zip
