---
apt_packages:
  - build-essential
  - git
  - curl
  - unzip
  - python3
  - python3-pip
  - snapd
  - ca-certificates
  - gnupg
  - awscli
  - docker.io
  - docker-compose-plugin
  - btop
  - fonts-martian-mono
  - fonts-droid-fallback
  - fonts-hack-ttf
  - dconf-cli
