vscode_extensions:
  - github.copilot
  - charliermarsh.ruff
  - ms-python.python
  - pyre-check.pyre-check
  - christian-kohler.path-intellisense
  - christian-kohler.npm-intellisense
  - ms-vscode.vscode-typescript-next
  - oderwat.indent-rainbow
  - eamodio.gitlens
  - github.copilot-chat
  - dsznajder.es7-react-js-snippets
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers
  - openai.openai-codex
  - biomejs.biome
  - BeardedBear.bearded-icons
  - formulahendry.auto-rename-tag

chrome_extensions:
  - edacconmaakjimmfgnblocblbcdcpbko # Session Buddy
  - nngceckbapebfimnlniiiahkandclblb # Bitwarden
  - gighmmpiobklfepjocnamgkkbiglidom # AdBlock
